### ISSUE TITLE
[Request] support for Dungeon Fantasy RPG

### ISSUE THREAD

**Issue by Syndaryl** [bmos/FG-CoreRPG-Coins-Weight#1]
Dungeon Fantasy RPG ("Powered by GURPS") by Steve Jackson Games [Link to company site](http://www.sjgames.com/dungeonfantasy/). Game abbreviation "DFRPG". A quirk of GURPS-derived games is that the value of things is expressed in $, regardless of the *actual* currency, which starts making sense when you look at the mess of currencies.

The core 4 coin types are all are standardized to 50/lb
> Copper, 1$, 0.02 lb
> Silver, 20$, 0.02 lb
> Gold, 400$, 0.02 lb
> Platinum, 800$, 0.02 lb

Secondarily, there are "fractional" gold coins (literally gold coins cut up like a pizza). The rules make jokes about sequins.
> 1/2 Gold, 200$, 0.01 lb
> 1/4 Gold, 100$, 0.005 lb
> 1/8 Gold, 50$, 0.0025 lb

The "also ran" coins are also standardized to 50/lb
> Billon, $10, 0.02 lb
> Tumbaga, $60, 0.02 lb
> Electrum, $200, 0.02 lb

Billon is copper/silver aloy, Tumbaga is copper/gold alloy, and Electrum is of course silver/gold alloy.

--

"GURPS Dungeon Fantasy" is a separate game, and for maximum confusion it uses a slightly different coin values. I'll make a separate request for it.

**Comment by bmos** [comment]
Sweet. I can definitely add these.
I assume for fractional coins you just input decimal numbers into coin fields but label them as "copper", "gold", etc?

**Comment by bmos** [comment]
https://github.com/bmos/FG-CoreRPG-Coins-Weight/releases/tag/v1.7

**Comment by bmos** [comment]
I added these and added a debug command which will help us track down the ruleset names if they aren't working yet.
If the denominations don't work, check the chat log immediately after loading your campaign. There will be a debug command present saying the name that your ruleset detects as.

**Comment by Syndaryl** [comment]
> 
> 
> Sweet. I can definitely add these.
> I assume for fractional coins you just input decimal numbers into coin fields but label them as "copper", "gold", etc?

Yes, it's so much simpler that way. :)

**Comment by bmos** [comment]
I actually went ahead and added them as you wrote them in your post in case people do want to track them individually from "whole" gold.
Nice to have choices. Thanks for contributing more currency definitions.
