### ISSUE TITLE
[Request] Support for GURPS Dungeon Fantasy

### ISSUE THREAD

**Issue by Syndaryl** [bmos/FG-CoreRPG-Coins-Weight#2]
GURPS Dungeon Fantasy by Steve Jackson Games [Link to company site](http://www.sjgames.com/gurps/books/dungeonfantasy/). Game abbreviation "GURPS DF" or "DF". A quirk of GURPS-derived games is that the value of things is expressed in $, regardless of the *actual* currency, which starts making sense when you look at the mess of currencies.

The core 4 coin types are not a standardized weight, unlike DFRPG.
> Copper farthing, 1$, 0.016 lb (62.5 per pound, yes really)
> Silver penny, 4$, 0.004 lb (250 per pound)
> Gold Piece, 80$, 0.004 lb (250 per pound)

The "also ran" coins are:
> Billon, $10, 0.02 lb (50 per pound)
> Tumbaga, $62, 0.02 lb (50 per pound)
> Electrum, $210, 0.02 lb (50 per pound)
> Platinum, 600$, 0.015625 lb (64 per pound, or 1/4 ounce each)

Billon is copper/silver aloy, Tumbaga is copper/gold alloy, and Electrum is of course silver/gold alloy. And yes, those are super annoying values.

**Comment by bmos** [comment]
seems to be duplicate

**Comment by bmos** [comment]
https://github.com/bmos/FG-CoreRPG-Coins-Weight/releases/tag/v1.7

**Comment by bmos** [comment]
I added these and added a debug command which will help us track down the ruleset names if they aren't working yet.
If the denominations don't work, check the chat log immediately after loading your campaign. There will be a debug command present saying the name that your ruleset detects as.
